# Generated by Django 6.0.6 on 2026-06-23 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED_BY_ML', 'Aprobada por ML'), ('REJECTED_BY_ML', 'Rechazada por ML')], default='PENDING', max_length=20)),
                ('risk_level', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10, null=True)),
                ('ml_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware_type', models.CharField(choices=[('gpu', 'Tarjeta de video'), ('cpu', 'Procesador'), ('ram', 'Memoria RAM'), ('ssd', 'SSD'), ('hdd', 'HDD'), ('psu', 'Fuente de poder'), ('motherboard', 'Placa madre'), ('cooler', 'Refrigeración')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
