# Generated by Django 6.0.6 on 2026-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='analysis_message',
            field=models.TextField(blank=True, help_text='Mensaje de análisis de estafa mostrado en el detalle.'),
        ),
    ]
