# Generated by Django 6.0.6 on 2026-06-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_analysis_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='analysis_sections',
            field=models.JSONField(blank=True, help_text='Secciones estructuradas del análisis ML.', null=True),
        ),
    ]
